"""empty message

Revision ID: 5d99bd48840a
Revises: 6cb322cf0416
Create Date: 2025-05-08 23:01:52.854144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d99bd48840a'
down_revision = '6cb322cf0416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=False))
        batch_op.drop_column('setupname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setupname', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
