"""empty message

Revision ID: 6cb322cf0416
Revises: f6805aae3df5
Create Date: 2025-05-08 15:19:32.116846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb322cf0416'
down_revision = 'f6805aae3df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setupname', sa.String(length=128), nullable=False),
    sa.Column('bemerkungen', sa.Text(), nullable=True),
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.Column('projekt_id', sa.Integer(), nullable=False),
    sa.Column('maschine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['maschine_id'], ['machine.id'], ),
    sa.ForeignKeyConstraint(['projekt_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setup')
    # ### end Alembic commands ###
