"""Add status column to setup

Revision ID: a714e9f684f4
Revises: 5d99bd48840a
Create Date: 2025-05-16 10:55:23.909171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a714e9f684f4'
down_revision = '5d99bd48840a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setup', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
